### ISSUE TITLE
Which num_points parameter to `ask()` ?

### ISSUE THREAD

**Issue by jlnav** [campa-consortium/generator_standard#2]
Options for method signature. I guess no option here implies control over how many points are returned?:

`ask(self) -> points`:

User has no implied control over how many points are returned.

`ask(self, num_points: int) -> points`:

User must specify some number of points when asking.

`ask(self, num_points: Optional[int] = 1) -> points`:

User may specify some number of points, but if not provided the default is 1.

`ask(self, num_points: Optional[int] = None) -> points`:

User may specify some number of points, but if not provided the default is None.

**Comment by RemiLehe** [comment]
From what I remember, the motivation for having `ask(self, num_points: int) -> points` is that some generators don't have a natural/default number of points to return. 

The example that was given was genetic algorithm (GA, Xopt: https://christophermayes.github.io/Xopt/api/generators/genetic/): when calling `ask(num_points)`, one would expect the GA to return the current best `num_points` in the population. @roussel-ryan Is that correct?

I guess that another example would be Bayesian optimization, where `num_points` could be generated at once (not equivalent to generating them serially). 

On the other hand, for all the above examples, the parameter `num_points` could also be passed in the constructor of the generator, no?

**Comment by RemiLehe** [comment]
After more discussion with @roussel-ryan, it seems that it would be better to **not** pass `num_points` to avoid confusion (since we discussed the fact that generators might in practice return more points or fewer points than `num_points` depending on the algorithm).

Instead, for generators that require information about the optimal number of points (e.g. batched Bayesian optimization: how many points to return in parallel ; GA: how many points in the population), we would pass this in the contructor of the class.

**Comment by RemiLehe** [comment]
After more discussion, it seems the preference would be to pass `num_points = None` as an optional argument:
`ask(self, num_points: Optional[int] = None) -> points`

- When it is not passed: the generator decides how many points to return. (different generators will return different number of points, by default: Simplex: 1 or 3 points, GA: returns the whole population, batched BO: specify a number of parallel points somewhere else e.g. constructor, then returns that number of points)

- When it is passed: the generator returns this number of points or fewer. In this case, it should return exactly this number of points, or raise a error (if it does not support this). (If the user is flexible about the number of points, it should simply not pass `num_points`.) Example use case: asynchronous workflows
